include $(GOROOT)/src/Make.inc

TARG = webrocket

GOFILES = \
	permission.go \
	message.go \
	connection.go \
	channel.go \
	context.go \
	endpoint.go \
	vhost.go \
	websocket_client.go \
	websocket_endpoint.go \
	websocket_handler.go \
	websocket_protocol.go \
	backend_agent.go \
	backend_agent_identity.go \
	backend_endpoint.go \
	backend_lobby.go

include $(GOROOT)/src/Make.pkg