include $(GOROOT)/src/Make.inc

TARG = webrocket
GOFILES = \
	user.go \
	context.go \
	errors.go \
	exchange.go \
	websocket_server.go \
	mq_server.go \
	channel.go \
	message.go \
	connection.go \
	websocket_api.go \
	vhost.go

include $(GOROOT)/src/Make.pkg