include $(GOROOT)/src/Make.inc

TARG = webrocket-admin
GOFILES = \
	main.go \
	utils.go \
	cmd_list_vhosts.go \
	cmd_add_vhost.go \
	cmd_delete_vhost.go \
	cmd_show_vhost.go \
	cmd_clear_vhosts.go \
	cmd_regenerate_vhost_token.go \
	cmd_list_channels.go \
	cmd_add_channel.go \
	cmd_delete_channel.go \
	cmd_clear_channels.go \
	cmd_list_workers.go

include $(GOROOT)/src/Make.cmd